module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "azul-marino": "var(--azul-marino)",
        "azul-vivo": "var(--azul-vivo)",
        blanco: "var(--blanco)",
        "color-primario-1": "var(--color-primario-1)",
        "color-primario-2": "var(--color-primario-2)",
        "color-secundario": "var(--color-secundario)",
        colorsblue: "var(--colorsblue)",
        colorsorange: "var(--colorsorange)",
        colorsteal: "var(--colorsteal)",
        darkbasebaseblack: "var(--darkbasebaseblack)",
        "graygray-100": "var(--graygray-100)",
        "gris-claro": "var(--gris-claro)",
        "gris-neutro": "var(--gris-neutro)",
        lightmodedangerdanger: "var(--lightmodedangerdanger)",
        "lightmodegreygrey-200": "var(--lightmodegreygrey-200)",
        "lightmodegreygrey-300": "var(--lightmodegreygrey-300)",
        "lightmodegreygrey-500": "var(--lightmodegreygrey-500)",
        "lightmodegreygrey-600": "var(--lightmodegreygrey-600)",
        "lightmodegreygrey-700": "var(--lightmodegreygrey-700)",
        "lightmodegreygrey-800": "var(--lightmodegreygrey-800)",
        "lightmodegreygrey-900": "var(--lightmodegreygrey-900)",
        lightmodelightlight: "var(--lightmodelightlight)",
        lightmodesuccesssuccess: "var(--lightmodesuccesssuccess)",
        "lightmodesuccesssuccess-active":
          "var(--lightmodesuccesssuccess-active)",
        "lightmodesuccesssuccess-clarity-20":
          "var(--lightmodesuccesssuccess-clarity-20)",
        "lightmodesuccesssuccess-light": "var(--lightmodesuccesssuccess-light)",
        "m3syslighton-primary": "var(--m3syslighton-primary)",
        "neutralneutral-0": "var(--neutralneutral-0)",
        "neutralneutral-100": "var(--neutralneutral-100)",
        "neutralneutral-20": "var(--neutralneutral-20)",
        "neutralneutral-50": "var(--neutralneutral-50)",
        "neutralneutral-60": "var(--neutralneutral-60)",
        "neutralneutral-90": "var(--neutralneutral-90)",
        "neutralneutral-95": "var(--neutralneutral-95)",
        "primaryprimary-11": "var(--primaryprimary-11)",
        "primaryprimary-8": "var(--primaryprimary-8)",
        secondarysecondary: "var(--secondarysecondary)",
        "textcolor-text": "var(--textcolor-text)",
        "textcolor-text-weakest": "var(--textcolor-text-weakest)",
        "texticoncolor-text-icon": "var(--texticoncolor-text-icon)",
        "texto-activoenfocado": "var(--texto-activoenfocado)",
        "texto-principal-oscuro": "var(--texto-principal-oscuro)",
        "texto-secundario": "var(--texto-secundario)",
        "utilities-figma-specifictransparent":
          "var(--utilities-figma-specifictransparent)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-b-11-12-500": "var(--body-b-11-12-500-font-family)",
        "body-b-12-12-500": "var(--body-b-12-12-500-font-family)",
        "body-b-14-14-500": "var(--body-b-14-14-500-font-family)",
        "body-b-14-22-400": "var(--body-b-14-22-400-font-family)",
        "body-b-16-16-600": "var(--body-b-16-16-600-font-family)",
        contenido: "var(--contenido-font-family)",
        "heading-h-30-30-600": "var(--heading-h-30-30-600-font-family)",
        "text-tiny-semi-bold": "var(--text-tiny-semi-bold-font-family)",
        titulos: "var(--titulos-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "widget-shadow": "var(--widget-shadow)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
